version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - ELASTIC_PASSWORD=changeme
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana-x-pack:6.2.3
    container_name: kibana
    environment:
      - SERVER_NAME=logging.mort3m.io
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - SERVER_BASEPATH=/kibana
    networks:
      - esnet
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch

  logging-backend:
    build: ./app/
    container_name: logging-backend
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    networks:
      - esnet
    ports:
      - "127.0.0.1:1337:1337"
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local

networks:
  esnet: